# Generated by Django 3.2.6 on 2022-11-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
